export const dataSelect = [
  "Any Category",
  "General Knowledge",
  "Entertaiment: Books",
  "Entertaiment: Film",
  "Entertaiment: Music",
  "Entertaiment: Musicals & Theatres",
  "Entertaiment: Television",
  "Entertaiment: Video Games",
  "Entertaiment: Board Games",
  "Science & Nature",
  "Science & Computers",
  "Science & Mathematics",
  "Mythology",
  "Sports",
  "Geography",
  "History",
  "Politics",
  "Art",
  "Celebrities",
  "Animals",
  "Vehicles",
  "Entertaiment: Comics",
  "Science: Gadgets",
  "Entertaiment: Japanese Anime & Manga",
  "Entertaiment: Cartoon & Animations",
];
